"use client";

import Link from "next/link";
import { ArrowDownLeft, ArrowUpRight, Plus, Sparkles, TrendingUp, Wallet } from "lucide-react";
import { useEffect, useState } from "react";
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { getAccounts, getBudgets, getCategories, getTransactions } from "@/lib/firestore";
import type { Account, Budget, Category, Transaction } from "@/lib/types";

const money = (value: number) => new Intl.NumberFormat("en-IE", { style: "currency", currency: "EUR" }).format(value);
const dateLabel = (date: string) => new Intl.DateTimeFormat("en-IE", { month: "short", day: "numeric" }).format(new Date(`${date}T00:00:00`));
function Panel({ title, children, action }: { title: string; children: React.ReactNode; action?: React.ReactNode }) { return <section className="surface p-5"><div className="mb-5 flex items-center justify-between"><h2 className="text-[15px] font-bold">{title}</h2>{action}</div>{children}</section>; }
function Stat({ title, value, icon: Icon, tone }: { title: string; value: string; icon: typeof Wallet; tone: string }) { return <div className="surface p-5"><div className="flex items-start justify-between"><div><p className="text-[13px] text-[var(--subtle)]">{title}</p><p className="mt-2 text-[25px] font-bold">{value}</p></div><div className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}><Icon size={18} /></div></div></div>; }

export default function Dashboard() {
    const [transactions, setTransactions] = useState<Transaction[]>([]);
    const [categories, setCategories] = useState<Category[]>([]);
    const [accounts, setAccounts] = useState<Account[]>([]);
    const [budgets, setBudgets] = useState<Budget[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");
    
    useEffect(() => { Promise.all([getTransactions(), getCategories(), getAccounts(), getBudgets()]).then(([t, c, a, b]) => { setTransactions(t); setCategories(c); setAccounts(a); setBudgets(b); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Unable to load dashboard data.")).finally(() => setLoading(false)); }, []);
    const categoryMap = new Map(categories.map((category) => [category.id, category]));
    const accountMap = new Map(accounts.map((account) => [account.id, account]));
    const income = transactions.filter((item) => item.type === "income").reduce((sum, item) => sum + item.amount, 0);
    const expenses = transactions.filter((item) => item.type === "expense").reduce((sum, item) => sum + item.amount, 0);
    const balance = accounts.reduce((sum, account) => sum + account.balance, 0);
    const byCategory = categories.map((category) => ({ name: category.name, value: transactions.filter((item) => item.type === "expense" && item.categoryId === category.id).reduce((sum, item) => sum + item.amount, 0), color: category.color })).filter((item) => item.value > 0);
    const byMonth = Array.from(new Set(transactions.map((item) => item.date.slice(0, 7)))).sort().slice(-6).map((month) => ({ month: new Intl.DateTimeFormat("en", { month: "short" }).format(new Date(`${month}-01T00:00:00`)), income: transactions.filter((item) => item.date.startsWith(month) && item.type === "income").reduce((sum, item) => sum + item.amount, 0), expenses: transactions.filter((item) => item.date.startsWith(month) && item.type === "expense").reduce((sum, item) => sum + item.amount, 0) }));
    if (loading) return <div className="grid gap-5"><div className="h-24 animate-pulse rounded-2xl bg-[var(--muted)]" /><div className="h-72 animate-pulse rounded-2xl bg-[var(--muted)]" /></div>;
    if (error) return <div className="surface p-8"><h1 className="text-xl font-bold">Could not load dashboard</h1><p className="mt-2 text-sm text-[var(--subtle)]">{error}</p></div>;
    return <><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-1 text-sm text-[var(--subtle)]">Your financial overview</p><h1 className="text-[28px] font-bold sm:text-[32px]">Good morning, Jamie</h1><p className="mt-1 text-sm text-[var(--subtle)]">Your numbers, grounded in Firestore.</p></div><Link href="/transactions" className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-[#295b55] px-4 text-sm font-semibold text-white"><Plus size={17} />Add transaction</Link></div>
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat title="Total balance" value={money(balance)} icon={Wallet} tone="bg-[#e4f2ed] text-[#295b55]" /><Stat title="Monthly income" value={money(income)} icon={ArrowDownLeft} tone="bg-[#fff0dd] text-[#bb762d]" /><Stat title="Monthly expenses" value={money(expenses)} icon={ArrowUpRight} tone="bg-[#fae8e4] text-[#c05c51]" /><Stat title="Savings" value={money(income - expenses)} icon={Sparkles} tone="bg-[#eeebfa] text-[#7767aa]" /></div>
        <div className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_1fr]"><Panel title="Income vs expenses"><div className="h-[260px]">{byMonth.length ? <ResponsiveContainer><AreaChart data={byMonth}><CartesianGrid stroke="var(--grid)" vertical={false} /><XAxis dataKey="month" /><YAxis tickFormatter={(value) => `€${value}`} /><Tooltip formatter={(value) => money(Number(value))} /><Area dataKey="income" stroke="#295b55" fill="#e4f2ed" /><Area dataKey="expenses" stroke="#e79a4d" fill="none" /></AreaChart></ResponsiveContainer> : <Empty text="No transactions yet" />}</div></Panel><Panel title="Spending by category"><div className="flex min-h-[190px] items-center gap-5">{byCategory.length ? <><div className="h-[190px] w-1/2"><ResponsiveContainer><PieChart><Pie data={byCategory} dataKey="value" innerRadius={52} outerRadius={78}>{byCategory.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip formatter={(value) => money(Number(value))} /></PieChart></ResponsiveContainer></div><div className="grid flex-1 gap-2 text-xs">{byCategory.map((item) => <div key={item.name} className="flex justify-between"><span>{item.name}</span><strong>{money(item.value)}</strong></div>)}</div></> : <Empty text="No expense data yet" />}</div></Panel></div>
        <div className="mt-5 grid gap-5 xl:grid-cols-[1fr_1.25fr]"><Panel title="Budget overview" action={<Link href="/budgets" className="text-xs font-semibold text-[#2b8069]">View all</Link>}>{budgets.length ? <div className="grid gap-5">{budgets.map((budget) => { const spent = transactions.filter((item) => item.type === "expense" && item.categoryId === budget.categoryId).reduce((sum, item) => sum + item.amount, 0); const percent = budget.amount ? Math.min(100, Math.round(spent / budget.amount * 100)) : 0; return <div key={budget.id}><div className="mb-2 flex justify-between text-sm"><span className="font-semibold">{categoryMap.get(budget.categoryId)?.name ?? "Unknown category"}</span><span className="text-xs text-[var(--subtle)]">{money(spent)} / {money(budget.amount)}</span></div><div className="h-2 rounded-full bg-[var(--muted)]"><div className="h-full rounded-full bg-[#295b55]" style={{ width: `${percent}%` }} /></div></div>; })}</div> : <Empty text="No budgets yet" />}</Panel><Panel title="Recent transactions" action={<Link href="/transactions" className="text-xs font-semibold text-[#2b8069]">View all transactions</Link>}>{transactions.length ? <div className="divide-y divide-[var(--line)]">{transactions.slice(0, 5).map((item) => <div key={item.id} className="flex items-center gap-3 py-3 first:pt-0"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[var(--muted)] text-[var(--subtle)]"><TrendingUp size={17} /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.description || "Transaction"}</p><p className="text-xs text-[var(--subtle)]">{categoryMap.get(item.categoryId)?.name ?? "Uncategorized"} · {accountMap.get(item.accountId)?.name ?? "Unknown account"} · {dateLabel(item.date)}</p></div><strong className={item.type === "income" ? "text-[#2b8069]" : ""}>{item.type === "income" ? "+" : "-"}{money(item.amount)}</strong></div>)}</div> : <Empty text="No transactions yet" />}</Panel></div></>;
}
function Empty({ text }: { text: string }) { return <div className="flex h-full min-h-24 flex-col items-center justify-center text-center text-sm text-[var(--subtle)]"><strong className="text-[var(--ink)]">{text}</strong><span className="mt-1">Add your first transaction to start tracking your finances.</span></div>; }
